// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define NO_ACTION_ONESHOT
#define MIDI_BASIC

#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_TWINKLE

#undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL

#define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define VIA_FIRMWARE_VERSION 0x1

#define USB_MAX_POWER_CONSUMPTION 100
