// Copyright 2023 Christopher Courtney, aka Drashna Jael're  (@drashna) <drashna@live.com>
// SPDX-License-Identifier: GPL-3.0-or-later

// #include "rgb/anim/startup_swirl_anim.h" // Requires matrix posistions to work
// #include "rgb/anim/my_party_rocks.h" // seizure warning
#include "rgb/anim/cool_diagonal.h"         // neaat
#include "rgb/anim/random_breath_rainbow.h" // rgb vomit!
// #include "rgb/anim/custom_gradient.h" // too custom
#include "rgb/anim/raindrops.h"
#include "rgb/anim/candy.h"
