// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /Users/drashna/Downloads/keyboard images/samurai-cyberpunk-minimal-dark-8k-b3-240x320.jpg --output /Users/drashna/repos/qmk_userspace/users/drashna/display/painter/graphics --format pal256 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_samurai_cyberpunk_minimal_dark_8k_b3_240x320_length;
extern const uint8_t  gfx_samurai_cyberpunk_minimal_dark_8k_b3_240x320[23934];
