SWAP_HANDS_ENABLE     = yes
AUTOCORRECT_ENABLE    = no
CAPS_WORD_ENABLE      = yes
SENTENCE_CASE_ENABLE  = yes
TAP_DANCE_ENABLE      = yes
BOOTMAGIC_ENABLE      = yes      # Enable Bootmagic Lite
CUSTOM_UNICODE_ENABLE = yes
WATCHDOG_ENABLE       = yes

BOOTLOADER = tinyuf2

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = custom
