// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /Users/drashna/Downloads/bkb_logo_mod.png --output /Users/drashna/repos/qmk_userspace/keyboards/bastardkb/dilemma/4x6_4/keymaps/drashna --format pal16 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_bkb_logo_mod_length;
extern const uint8_t  gfx_bkb_logo_mod[7620];
