// Copyright 2023 Christopher Courtney, aka Drashna Jael're  (@drashna) <drashna@live.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#define CIRQUE_PINNACLE_SPI_DIVISOR 8
#define CIRQUE_PINNACLE_SPI_CS_PIN  POINTING_DEVICE_CS_PIN

#define CIRQUE_PINNACLE_TAP_ENABLE
#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE

#define OLED_DISPLAY_128X128
#define OLED_UPDATE_PROCESS_LIMIT 2

#define ENCODER_RESOLUTION 2

#undef RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 750U

#define DISPLAY_DC_PIN  GP11
#define DISPLAY_CS_PIN  GP12
#define DISPLAY_RST_PIN GP13

#define OLED_DC_PIN  GP11
#define OLED_CS_PIN  GP12
#define OLED_RST_PIN GP13

#define OLED_SPI_DIVISOR 16

#define DILEMMA_DEBUG_1 GP16
#define DILEMMA_DEBUG_2 GP18
