// Copyright 2024 Christopher Courtney, aka Drashna Jael're  (@drashna) <drashna@live.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#ifndef QUANTUM_PAINTER_DISPLAY_TIMEOUT
#    define QUANTUM_PAINTER_DISPLAY_TIMEOUT 3600000
#endif

#ifndef QUANTUM_PAINTER_NUM_IMAGES
#    define QUANTUM_PAINTER_NUM_IMAGES 64
#endif // QUANTUM_PAINTER_NUM_IMAGES
#ifndef QUANTUM_PAINTER_SUPPORTS_256_PALETTE
#    define QUANTUM_PAINTER_SUPPORTS_256_PALETTE TRUE
#endif // QUANTUM_PAINTER_SUPPORTS_256_PALETTE
#ifndef QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS
#    define QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS TRUE
#endif // QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS
#ifndef QUANTUM_PAINTER_PIXDATA_BUFFER_SIZE
#    define QUANTUM_PAINTER_PIXDATA_BUFFER_SIZE 4096
#endif // QUANTUM_PAINTER_PIXDATA_BUFFER_SIZE
