// Copyright 2022 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-3.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image -i font.png -f mono2`

#pragma once

#include <qp.h>

extern const uint32_t font_ubuntu_10_font_length;
extern const uint8_t  font_ubuntu_10_font[2598];
extern const uint32_t font_ubuntu_mono_12_font_length;
extern const uint8_t  font_ubuntu_mono_12_font[2650];
extern const uint32_t font_thintel15_length;
extern const uint8_t  font_thintel15[966];
