// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /Users/drashna/Downloads/keyboard images/anime-girl-jacket-240x320.jpg --output /Users/drashna/repos/qmk_userspace/users/drashna/painter/graphics --format pal256 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_anime_girl_jacket_240x320_length;
extern const uint8_t  gfx_anime_girl_jacket_240x320[72542];
