// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /Users/drashna/repos/qmk_userspace/users/drashna/painter/matrix.gif --output /Users/drashna/repos/qmk_userspace/users/drashna/painter/graphics --format pal16 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_matrix_length;
extern const uint8_t  gfx_matrix[1706051];
